# Generated by Django 5.2.6 on 2025-10-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_chat_options_chat_is_rag_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='faiss_index_path',
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
