# Generated by Django 5.2.6 on 2025-10-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_chatsession_faiss_index_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='embedding',
        ),
    ]
