# Generated by Django 5.2.6 on 2025-10-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_documentchunk_embedding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
    ]
