# Generated by Django 5.2.6 on 2025-10-07 16:19

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_documentchunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=myapp.models.document_upload_path),
        ),
    ]
