# Generated by Django 5.2.6 on 2025-10-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='faiss_index_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='faiss_index_pickle',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
